stages:
  - package

cache:
  paths:
    - ffmpeg-*.tar.bz2

.package: &package
  stage: package
  script:
    - JOB_NAME=($CI_BUILD_NAME)
    - ARCH=${JOB_NAME[1]} ./build-${JOB_NAME[1]}.sh
  artifacts:
    paths:
      - ffmpeg-*-audio-*-*
    expire_in: 7d

.package-docker: &package-docker
  <<: *package
  image: docker.oxygene.sk/acoustid/chromaprint-build
  tags:
    - docker

#linux i686: *package-docker
#linux x86_64: *package-docker
#linux armhf:
#  <<: *package
#  tags:
#    - raspberrypi

#windows i686: *package-docker
#windows x86_64: *package-docker

.package-macos: &package-macos
  <<: *package
  tags:
    - osx

#macos i386: *package-macos
#macos x86_64: *package-macos

.package-android: &package-android
  <<: *package-docker
  image: docker.oxygene.sk/acoustid/chromaprint-build:android

android armeabi: *package-android
#android armeabi-v7a: *package-android
